[project]
name = "mana_curve"
version = "0.1.0"
description = "Utilities for deckbuilding"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pyrchidekt>=2.1.0",
    "scrython>=1.11.0",
    "tabulate>=0.9.0",
    "tqdm>=4.67.1",
]
